apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml

images:
- name: registry.npf.dk/steam-token-handler
  newName: registry.npf.dk/steam-token-handler
  newTag: 20201012-002130
